name: First Workflow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print greeting and goodbye
        run: | 
            echo "Hello peace of shit!"
            echo "Bye, peace of shit!"
      - name: Print some shit
        run: |
            echo "Done - get out!"
            echo "I think you'are an asshole"
